server:
  port: 7777

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/userdb?createDatabaseIfNotExist=true
                                  #&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Turkey
    username: root
    password: ali45
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: auth-service
  config:
    import: config-server:http://${CONFIG_SERVER_URL:localhost}:9296

jwt:
  secret: mySecretKey
  expireMs: 120000
  refreshExpireMs: 120000
