server:
  port: 7777

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/userdb?createDatabaseIfNotExist=true
                                  #&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Turkey
    username: root
    password: ali45
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: auth-service
  config:
    import: config-server:http://${CONFIG_SERVER_URL:localhost}:9296

jwt:
  secret: 488883bb806dbd6c78fdb2154fbf1e2ae54dbd6ca82d06da0d9a47111b56f738
      # encryption key
  expireMs: 120000
  refreshExpireMs: 86400000L
