spring:
  zipkin:
    baseUrl: http://zipkin-svc:9411
  application:
    name: CONFIG-SERVER


  profiles:
      active: native    #local repository. if you want external repo, replace it with "git"

server:
    port: 9296


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}


#  cloud:
#    config:
#      server:
#        git:
#          username: 
#          password:
#          uri: https://github.com/
#          clone-on-start: true


