spring:
  application:
    name: config-server

#  cloud:
#    config:
#      server:
#        git:
#          username: Rapter1990
#          password:
#          uri: https://github.com/Rapter1990/springappconfig
#          clone-on-start: true

  profiles:
    active: native

server:
  port: 9296



